# Generated by Django 4.1.6 on 2023-02-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_education_mobitype_rang_body_education_body_mobitype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='body',
            name='ethnos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ethnos'),
        ),
    ]
