# Generated by Django 4.1.6 on 2023-02-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ethnos_body_ethnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='body',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата смерти'),
        ),
        migrations.AddField(
            model_name='body',
            name='flag_done',
            field=models.BooleanField(default=False, verbose_name='проверено'),
        ),
        migrations.AddField(
            model_name='body',
            name='origin_url',
            field=models.URLField(blank=True, null=True, verbose_name='линк-источник'),
        ),
        migrations.AddField(
            model_name='body',
            name='oririgin_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='копия экрана'),
        ),
    ]
