# Generated by Django 4.1.6 on 2023-02-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_body_birth_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('txt', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=9, verbose_name='Contact Phone')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Website Address')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
            ],
        ),
        migrations.AlterField(
            model_name='body',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.army'),
        ),
        migrations.AlterField(
            model_name='body',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.education'),
        ),
        migrations.AlterField(
            model_name='body',
            name='ethnos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ethnos'),
        ),
        migrations.AlterField(
            model_name='body',
            name='mobitype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mobitype'),
        ),
        migrations.AlterField(
            model_name='body',
            name='rang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rang'),
        ),
        migrations.AlterField(
            model_name='body',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
    ]
